INFO:root:Посещена страница 'о себе'
INFO:root:Посещена страница 'о себе'
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_ptoject\myproject\myproject\settings.py changed, reloading.
INFO:root:Посещена страница 'о себе'
INFO:django.server:"GET /about/ HTTP/1.1" 200 308
INFO:root:Посещена страница 'о себе'
INFO:django.server:"GET /about/ HTTP/1.1" 200 308
INFO:root:Посещена страница 'о себе'
INFO:django.server:"GET /about/ HTTP/1.1" 200 308
INFO:root:Посещена страница 'о себе'
INFO:django.server:"GET /about/ HTTP/1.1" 200 308
INFO:root:Посещена страница 'о себе'
INFO:django.server:"GET /about/ HTTP/1.1" 200 308
INFO:root:Посещена главная страница
INFO:django.server:"GET / HTTP/1.1" 200 388
INFO:root:Посещена страница 'о себе'
INFO:django.server:"GET /about/ HTTP/1.1" 200 308
INFO:root:Посещена главная страница
INFO:django.server:"GET / HTTP/1.1" 200 388
INFO:root:Посещена главная страница
INFO:django.server:"GET / HTTP/1.1" 200 388
INFO:root:Посещена главная страница
INFO:django.server:"GET / HTTP/1.1" 200 388
INFO:root:Посещена главная страница
INFO:django.server:"GET / HTTP/1.1" 200 388
INFO:root:Посещена главная страница
INFO:django.server:"GET / HTTP/1.1" 200 388
INFO:root:Посещена главная страница
INFO:django.server:"GET / HTTP/1.1" 200 388
INFO:root:Посещена главная страница
INFO:django.server:"GET / HTTP/1.1" 200 388
INFO:root:Посещена страница 'о себе'
INFO:django.server:"GET /about/ HTTP/1.1" 200 308
INFO:root:Посещена страница 'о себе'
INFO:django.server:"GET /about/ HTTP/1.1" 200 308
INFO:root:Посещена страница 'о себе'
INFO:django.server:"GET /about/ HTTP/1.1" 200 308
INFO:root:Посещена главная страница
INFO:django.server:"GET / HTTP/1.1" 200 388
INFO:root:Посещена главная страница
INFO:django.server:"GET / HTTP/1.1" 200 388
INFO:root:Посещена главная страница
INFO:django.server:"GET / HTTP/1.1" 200 388
INFO:root:Посещена страница 'о себе'
INFO:django.server:"GET /about/ HTTP/1.1" 200 308
INFO:root:Посещена главная страница
INFO:django.server:"GET / HTTP/1.1" 200 388
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.server:"GET /favicon.ico HTTP/1.1" 404 2548
INFO:root:Посещена страница 'о себе'
INFO:django.server:"GET /about/ HTTP/1.1" 200 308
INFO:django.server:"GET /admin/ HTTP/1.1" 302 0
INFO:django.server:"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
INFO:django.server:"GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO:django.server:"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO:django.server:"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO:django.server:"GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO:django.server:"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO:django.server:"GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO:django.server:"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
WARNING:django.request:Not Found: /myapp2/
WARNING:django.server:"GET /myapp2/ HTTP/1.1" 404 2536
INFO:root:Посещена страница myapp2
INFO:django.server:"GET /myapp3/ HTTP/1.1" 200 337
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:root:Посещена страница myapp2
INFO:django.server:"GET /myapp3/ HTTP/1.1" 200 337
INFO:root:Посещена страница myapp2
INFO:django.server:"GET /myapp3/ HTTP/1.1" 200 337
INFO:root:Посещена главная страница
INFO:django.server:"GET / HTTP/1.1" 200 388
INFO:root:Посещена главная страница
INFO:django.server:"GET / HTTP/1.1" 200 388
WARNING:django.request:Not Found: /myapp2/
WARNING:django.server:"GET /myapp2/ HTTP/1.1" 404 2536
INFO:root:Посещена страница myapp2
INFO:django.server:"GET /myapp3/ HTTP/1.1" 200 337
INFO:root:Посещена страница myapp2
INFO:django.server:"GET /myapp3/ HTTP/1.1" 200 337
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:root:Посещена страница myapp2
INFO:django.server:"GET /myapp3/ HTTP/1.1" 200 337
INFO:django.server:"GET /myapp3/client_orders/3/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/1/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/2/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
ERROR:django.request:Internal Server Error: /myapp3/client_orders/52/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py", line 11, in client_orders
    client = Client.objects.get(pk=client_id)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
myapp3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR:django.server:"GET /myapp3/client_orders/52/ HTTP/1.1" 500 74918
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/42 HTTP/1.1" 301 0
ERROR:django.request:Internal Server Error: /myapp3/client_orders/42/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py", line 11, in client_orders
    client = Client.objects.get(pk=client_id)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
myapp3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR:django.server:"GET /myapp3/client_orders/42/ HTTP/1.1" 500 74918
INFO:django.server:"GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:django.server:"GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/4/ HTTP/1.1" 200 436
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:django.server:"GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO:root:Посещена главная страница
INFO:django.server:"GET / HTTP/1.1" 200 388
WARNING:django.request:Not Found: /myapp2/
WARNING:django.server:"GET /myapp2/ HTTP/1.1" 404 2536
WARNING:django.request:Not Found: /myapp2/3
WARNING:django.server:"GET /myapp2/3 HTTP/1.1" 404 2539
WARNING:django.request:Not Found: /myapp2/
WARNING:django.server:"GET /myapp2/ HTTP/1.1" 404 2536
WARNING:django.request:Not Found: /myapp2/client_orders/5/
WARNING:django.server:"GET /myapp2/client_orders/5/ HTTP/1.1" 404 2584
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
WARNING:django.request:Not Found: /myapp3/client_orders/
WARNING:django.server:"GET /myapp3/client_orders/ HTTP/1.1" 404 2852
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myproject\urls.py changed, reloading.
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /myapp3/client_orders/10/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py", line 18, in client_orders
    seven_days_ago = timezone.now() - timedelta(days=7)
NameError: name 'timezone' is not defined
ERROR:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 500 66301
ERROR:django.request:Internal Server Error: /myapp3/client_orders/10/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py", line 18, in client_orders
    seven_days_ago = timezone.now() - timedelta(days=7)
NameError: name 'timezone' is not defined
ERROR:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 500 66301
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /myapp3/client_orders/10/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py", line 32, in client_orders
    return render(request, 'orders.html', context)
NameError: name 'render' is not defined
ERROR:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 500 67772
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/1 HTTP/1.1" 301 0
INFO:django.server:"GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /myapp3/client_orders/1/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py", line 16, in client_orders
    seven_days_ago = timezone.now() - timedelta(days=7)
AttributeError: type object 'datetime.timezone' has no attribute 'now'
ERROR:django.server:"GET /myapp3/client_orders/1/ HTTP/1.1" 500 66453
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:django.server:"GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:root:Посещена страница myapp3
INFO:django.server:"GET /myapp3/ HTTP/1.1" 200 337
WARNING:django.request:Not Found: /myapp3/2
WARNING:django.server:"GET /myapp3/2 HTTP/1.1" 404 2813
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.utils.autoreload:C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO:django.server:"GET /myapp3/client_orders/10/ HTTP/1.1" 200 388
